development:
  adapter: postgresql
  encoding: unicode
  database: translatior_gem_development
  username: hassan
  password:
  timeout: 5000
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: translatior_gem_test
  username: hassan
  password:
  timeout: 5000
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: translatior_gem
  username: deployer
  password:
  timeout: 5000
  pool: 5
