development:
  adapter: postgresql
  encoding: unicode
  database: translatior_gem_development
  username: postgres
  password:
  timeout: 5000
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: translatior_gem_test
  username: postgres
  password:
  timeout: 5000
  pool: 5
